### ISSUE TITLE
Classify GO terms in their aspect

### ISSUE THREAD

**Issue by mcourtot** [ebi-uniprot/QuickGoFE#104]
I often have list of GO terms that user would like to classify into CC, MF or BP. Do we have a tool that allows to do that, or would it be easy to add?

For example from 
```
GO:0000015
GO:0000045
GO:0000049
GO:0000062
GO:0000075
GO:0000079
GO:0000096
GO:0000104
GO:0000105
GO:0000107
GO:0000139
GO:0000145
GO:0000154
GO:0000159
GO:0000160
GO:0000166
GO:0000172
GO:0000175
GO:0000178
```

I'd like to get

```
C	GO:0000015
C	GO:0000139
C	GO:0000145
C	GO:0000159
C	GO:0000172
C	GO:0000178
P	GO:0000045
P	GO:0000075
P	GO:0000079
P	GO:0000096
P	GO:0000105
P	GO:0000154
P	GO:0000160
F	GO:0000049
F	GO:0000062
F	GO:0000104
F	GO:0000107
F	GO:0000166
F	GO:0000175
```

**Comment by xwatkins** [comment]
Mmmm I think you should be able to do that by using the "upload your own" on the slimming page. Not ideal but should give you what you want.

**Comment by mcourtot** [comment]
Hmm - I tried and went to http://www.ebi.ac.uk/QuickGO-Beta/slimming
I enter my list of terms in the text field, and can visualise the chart but the 'Add your Terms' button doesn't work (Safari or Chrome)
I can do the classification this way in the old QuickGO (https://www.ebi.ac.uk/QuickGO/GMultiTerm#tab=choose-terms) but can't download the list, so not very useful (the above is an excerpt of a list of ~1000 terms - most cases users send us their list of annotated GO terms which are usually in that order of magnitude)

**Comment by mcourtot** [comment]
Maybe a web service would be easy to add? I don't know what is the status on programmatic access to QuickGO though.

**Comment by xwatkins** [comment]
The beta is out of date while we're moving to the new backend (very nearly there) so the "Add your terms" will be working, but that doesn't solve the issue with download (but this could potentially be added)
With the web service you will be able to programmatically get a list of go terms, which includes its aspect but you would have to do the grouping yourself so again not very easy.

**Comment by mcourtot** [comment]
A download sounds like a great idea - if users try and add/remove their own terms it would make sense that they would want to download them afterwards.
Thanks for the feedback!

**Comment by xwatkins** [comment]
I will create a Jira issue.
